### PR TITLE
Attempt to fix the Win32 build.

### PR DESCRIPTION
**Pull request by pkgw**
Commentary to follow, if this actually works.

### CODE REVIEW

**Comment by pkgw** [comment]
OK, well, I'll write up some notes on what seems to be going on here.

First, there seems to be a disagreement between the Cygwin settings in the Miniconda distribution, and in the Cygwin tools that are installed during the conda-build process. The Miniconda version of `cygpath` maps Windows drives to Unix ones with a special fake prefix of `/cygdrive`:

```
> c:\Miniconda3\Library\usr\bin\cygpath.exe c:\Miniconda3
/cygdrive/c/Miniconda3
```

The `cygpath` inside the build process doesn't have the fake prefix:

```
> c:\Miniconda3\conda-bld\recipe_NNNNN\_b_env\Library\usr\bin\cygpath.exe c:\Miniconda3
/c/Miniconda3
```

This becomes relevant because the relevant programs later map these Unix paths back into Windows paths. Some `bld.bat` scripts use the `cygpath` program to make Unix paths out of Windows paths; if those are run using the Miniconda `cygpath` (which I believe happens unless `%PATH%` gets futzed with), Cygwin tools inside the build environment will not un-map them correctly.

**Second**, the particular build process used for `cairo` is a bit tricky. The `bld.bat` script launches `make`, which then invokes the Windows C/C++ compiler `cl`. MSYS2 has special logic so that when a Unix-native program like `make` invokes a Windows-native program like `cl`, any paths in the program's command line arguments are mapped back to Windows-type paths. The environment variable `MSYS2_ARG_CONF_EXCL` controls which arguments are affected by this substitution. For reasons I don't fully understand, in my tests, clearing this variable got the Cairo build to work again.

Finally, I'm not sure exactly when it happened, but I think that a somewhat recent version of `conda-build` added a command to automatically set `MSYS2_ARG_CONF_EXCL` in the Windows build script preamble. I haven't looked up exactly when that happened but something came up when I googled — gotta run so can't find it again right now.

**Comment by pkgw** [comment]
For reference, here are relevant the commits in the Git history of `conda-build` that alter text relating to the MSYS2 magic variables:

```
7c20b85 revert MSVC disutils changes
829eb86 revert MSVC disutils changes
948d7c2 add --no-activate option to bypass activation
565e5f5 add another MSYS2 exclusion
90818eb move MSYS2 exclude stuff higher, so that it doesn't reset error level
b577fa7 dumb extra character in MSYS2 exclude var setting
2286cf7 change slash-to-dash to MSYS2_ARG_CONV_EXCL
```

**Comment by pkgw** [comment]
Aha! The trailing semicolon in the definition of `MSYS2_ARG_CONV_EXCL` seems to be the culprit here. I have an example on the VM I'm using to test where I can put it in and take it out, and the build succeeds or fails depending on whether it's present (failure) or absent (success).

I suspect that MSYS2 is parsing the variable into a string of zero length and then deciding to convert no command-line arguments to any Windows programs. I'll file this as a conda-build bug since that's not the intended behavior; the trailing semicolon comes from expanding a possibly-absent previous value of the variable.

**Comment by pkgw** [comment]
There's some related discussion in [this conda-build pull request](https://github.com/conda/conda-build/pull/1651).

**Comment by ccordoba12** [comment]
Great job, this is passing now!

**Comment by ccordoba12** [comment]
Could you also remove my suggested hack

https://github.com/conda-forge/cairo-feedstock/blob/master/appveyor.yml#L83

as part of this PR?

**Comment by pkgw** [comment]
The CI failures were because I accidentally pushed my branch to the `conda-forge` user's GitHub account and somehow the two sets of checks get combined. So, I'm going ahead and merging.

**Pull request merged**
