### PR TITLE
Move to conda-build 3

### PR DESCRIPTION
**Pull request by pkgw**
Build is currently failing in the Linux containers due to a linking problem in the system libraries ... the CI output shows problems with redefining XRender symbols, but I believe the proximate cause is this message in `config.log`:

```
configure:22839: checking for XRenderCreateLinearGradient
configure:22839: gcc -o conftest [....] conftest.c -lrt  -lm   -lSM -lICE  -lX11 -lXext   -lXrender >&5
/usr/lib/../lib64/libSM.so: undefined reference to `uuid_unparse_lower@UUID_1.0'
/usr/lib/../lib64/libSM.so: undefined reference to `uuid_generate@UUID_1.0'
collect2: error: ld returned 1 exit status
```

Not sure why this has started happening. Could perhaps be avoided by using conda-forge's X libraries, [but that has been controversial](https://github.com/conda-forge/cairo-feedstock/pull/23).

### CODE REVIEW

**Comment by pkgw** [comment]
Actually, the host environment does include `libuuid`, so the build stage is probably trying to link libSM with that rather than the system libuuid. It looks like `fontconfig` is the package with the internal `libuuid` dependency.

Using conda-forge's X libraries for the Linux build would be one way to avoid this, I think.

**Comment by bgruening** [comment]
I'm all for it to merge it! :)

**Comment by pkgw** [comment]
Me too. Any comments on the issues alluded to above, @conda-forge/staged-recipes folks?

**Comment by pkgw** [comment]
(FYI, I just force-pushed with a package name fix (`xorg-xcb-proto` is deprecated for `xcb-proto`) and some tidying of the history. Should definitely still pass CI ...)

**Comment by sodre** [comment]
LGTM

**Comment by bgruening** [comment]
Thanks @pkgw and @sodre for the review.

**Pull request merged**
