### PR TITLE
Update and build Windows packages

### PR DESCRIPTION
**Pull request by ocefpaf**
@mingwandroid can you take a quick look at the Windows build? it seems that `posix` and `m2w64-xz` was all we needed.

### CODE REVIEW

**Comment by ccordoba12** [comment]
Glad to see support for Windows here :-)

**Comment by ocefpaf** [comment]
> Glad to see support for Windows here :-)

Thank @mingwandroid's awesome work on the `msys2` package that made it possible.

**Comment by ccordoba12** [comment]
Thanks Ray!

**Comment by mingwandroid** [comment]
Thanks guys, but the `MSYS2` project did all the work really (OK I'm on that project but there's nearly 200 other contributors too!).

**Comment by ccordoba12** [comment]
Merge? This one looks ready to me :-)

**Comment by ocefpaf** [comment]
Yes please :wink:

**Comment by ccordoba12** [comment]
Here we go!

**Pull request merged**
