### PR TITLE
Windows improvements: build cairo-gobject and add pkg-config files

### PR DESCRIPTION
**Pull request by ryanvolz**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

These improvements are necessary (or in the case of the pkg-config files, very helpful) on the way to enabling a Windows build for `gtk3`.

### CODE REVIEW

**Comment by ryanvolz** [comment]
I'll take feedback about what to do for the vs2008 build, which fails because `glib` isn't available. I could get it going again by skipping the cairo-gobject support in that case, or vs2008 support altogether could be dropped.

**Comment by jakirkham** [comment]
Would skip it like so.

```yaml
build:
  ...
  skip: true    # [win and vc<14]
```

Note we are about to drop it soon. ( https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/491 )

**Comment by ryanvolz** [comment]
> Would skip it like so.
> 
> ```yaml
> build:
>   ...
>   skip: true    # [win and vc<14]
> ```
> 
> Note we are about to drop it soon. ( [conda-forge/conda-forge-pinning-feedstock#491](https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/491) )

Great! This is now ready for review/merge.

**Comment by pkgw** [comment]
@ryanvolz Thanks for this! Just a quick check — have you been able to test this build locally and verify that the new features in the Windows package seem to be working?

**Comment by ryanvolz** [comment]
> @ryanvolz Thanks for this! Just a quick check — have you been able to test this build locally and verify that the new features in the Windows package seem to be working?

I haven't quite gotten my application of interest (`gnuradio-companion`) to build yet locally, so I'm not sure that the `cairo-gobject` portion is working yet. If anyone knows of an easier way to test the functionality other than building an application that uses it, I can do that test. I'll keep trying with `gnuradio-companion` in the meantime. The `pkg-config` additions are working fine locally and have been successfully picked up for downstream package builds.

**Comment by pkgw** [comment]
@ryanvolz OK, we'll put this out here and see how it works ...

**Pull request merged**
