### PR TITLE
Attempt to add freetype support on Windows

### PR DESCRIPTION
**Pull request by oschwartz10612**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Attempted fix of #26 

Edit: It appears that this build correctly but I am not sure how to test?

### CODE REVIEW

**Comment by pkgw** [comment]
@oschwartz10612 Looks like the build failure is currently because the Win32 features patch has the wrong filename — it needs to include the file's path within the tarball.

**Comment by oschwartz10612** [comment]
Thanks. I have been working on and off on this as I have time and haven't had a chance to analyze the issue.

**Comment by oschwartz10612** [comment]
This build appears successful?

**Comment by oschwartz10612** [comment]
@conda-forge-admin, please rerender

**Comment by pkgw** [comment]
Great, it builds! Looking over everything, it looks to me like the `windows_pc_files.patch` file should have a `cairo-ft.pc` added. Other than that, I think this is ready to go. Next step would be to work on poppler-feedstock and iterate as needed.

**Comment by oschwartz10612** [comment]
Great! Will fix tomorrow.

Thanks for taking the time to work with me. Great learning experience.

**Comment by oschwartz10612** [comment]
Was this done correctly? I copied the conventions of previous entries.

**Comment by pkgw** [comment]
I think the issue causing the build failure was merely a missing newline in the last line of the patch file.

However, the contents of the .pc file should have been a little different, from looking at the Cairo source and my own system. I've pushed a commit to your branch that should bring it into order, I think.

**Comment by oschwartz10612** [comment]
I see now what this was supposed to be patching. Thanks for fixing the issues. 

Appears that the failure was a HTTP error with the Cairo website so I think that is fine. Possible to merge?

**Comment by pkgw** [comment]
I think this is ready to merge. @ccordoba12 @ocefpaf @jakirkham any feedback?

**Pull request merged**
