### PR TITLE
Pin freetype...

### PR DESCRIPTION
**Pull request by ocefpaf**
... and rerender the feedstock.

Ideally we should merge https://github.com/conda-forge/fontconfig-feedstock/pull/3 first!

### CODE REVIEW

**Comment by jakirkham** [comment]
Ouch! Well, this will be fun to dig into. Can't promise to do it soon.

**Comment by ocefpaf** [comment]
We need to recruit more Mac guys :wink:

**Comment by jakirkham** [comment]
Let's try restarting the CIs and seeing if maybe it is just because of some incompatibilities centered around `freetype`.

**Comment by jakirkham** [comment]
Could you please try adding `libiconv`?

**Comment by jakirkham** [comment]
NVM already being pulled in.

**Comment by jakirkham** [comment]
Seems like one of the packages has a bad libtool file. Maybe it proceeds the Homebrew changes.

**Comment by jakirkham** [comment]
Something is picking up `libiconv` in the wrong place.

```
libtool: link: cannot find the library `/usr/lib/libiconv.la' or unhandled argument `/usr/lib/libiconv.la'
```

**Comment by jakirkham** [comment]
It's `libxml2`, which has the bad path in its `libtool` file `libxml2.la`. That is also coming from `defaults`. Will check to see if ours is any better on this front.

**Comment by jakirkham** [comment]
Using our `libxml2` does indeed fix it, but there is another pinning problem we should address here too. It is picking up the wrong `xz`, which is probably why we are in this situation to begin with. Will put together a PR.

**Comment by jakirkham** [comment]
Ah, sorry, was forgetting `xz` is just used for decompression here.

**Comment by jakirkham** [comment]
Long story short, ignore the comments about my thought process above and just read and look at this PR ( https://github.com/conda-forge/cairo-feedstock/pull/4 ).

**Pull request merged**
