### PR TITLE
Update ICU pin

### PR DESCRIPTION
**Pull request by ocefpaf**
cc @mingwandroid

### CODE REVIEW

**Comment by ocefpaf** [comment]
Linux passed but this is worrisome:

```
not found:
    libicudata.so.56 (not found)
    libicui18n.so.56 (not found)
    libicuuc.so.56 (not found)
```

Not sure where that is coming from :confused:

**Comment by pkgw** [comment]
Looks like it's fontconfig:

```
/opt/rh/devtoolset-2/root/usr/libexec/gcc/x86_64-redhat-linux/4.8.2/ld: warning: libicui18n.so.56, needed by /feedstock_root/build_artefacts/recipe_root_1485970178252/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/lib/libfontconfig.so.1, not found (try using -rpath or -rpath-link)
```

**Comment by ocefpaf** [comment]
Thanks @pkgw `fontconfig` was not in my list b/c I did not see a direct dependency on `icu`, but I see now I need to re-build more stuff before this one.

**Comment by ocefpaf** [comment]
Needs https://github.com/conda-forge/libxml2-feedstock/pull/25 and fontconfig.

**Comment by pkgw** [comment]
Looks good to merge. Why are you skipping this on `win and py>35`? is there some problem with ICU on Python 3.6?

**Comment by ocefpaf** [comment]
> Looks good to merge. Why are you skipping this on `win and py>35`? is there some problem with ICU on Python 3.6?

No problem. We just don't need `vc 14` twice. We would need that only if cairo had a `run` time dependency on `Python`.

**Comment by ocefpaf** [comment]
@pkgw let's wait for https://github.com/conda-forge/fontconfig-feedstock/pull/16 first to ensure `icu 58.*` will be used.

**Pull request merged**
