### PR TITLE
Start building GObject bindings.

### PR DESCRIPTION
**Pull request by pkgw**
Does what it says.

### CODE REVIEW

**Comment by ocefpaf** [comment]
@pkgw can you navigate to https://circleci.com/gh/pkgw/cairo-feedstock , click on `follow project`, and then send an empty commit here? That should activate CircleCI. recently CircleCI changed how they start tests on forks and we need that workaround until we figure out a better way :unamused: 

PS: consider adding yourself as a maintainer.

**Comment by ccordoba12** [comment]
The problem seems the change in the conda-build version used when Windows packages were successfully compiled last time (#14, conda-build 2.0.11) and this PR (conda-build 2.0.12).

@ocefpaf, could this be the cause?

@pkgw, please pin conda-build to 2.0.11 in appveyor.yml and try again to see what happens.

**Comment by pkgw** [comment]
That doesn't seem to have helped. The value of `PIXMAN_CFLAGS` getting fed into the Makefile seems reasonable, so I'm confused.

**Comment by ocefpaf** [comment]
> @ocefpaf, could this be the cause?

That's odd. Either wau your original changes are completely unrelated to Windows, So let's get only those merged and deal with Windows later.

**Comment by ocefpaf** [comment]
I debug Windows in another PR. Let's get this merged.

**Pull request merged**
